# Generated by Django 5.1.3 on 2024-11-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vnet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vnet_name", models.CharField(max_length=100)),
                ("address_space", models.CharField(max_length=100)),
                ("resource_group", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("project_name", models.CharField(max_length=100)),
            ],
        ),
    ]
